# Generated by Django 5.2 on 2025-04-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camaras',
            fields=[
                ('idcamara', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecamara', models.CharField(max_length=100)),
                ('ipcamar', models.CharField(max_length=100)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'camaras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detalleusuariocamara',
            fields=[
                ('iddetalle', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
            ],
            options={
                'db_table': 'detalleusuariocamara',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipocamara',
            fields=[
                ('idtipocamara', models.AutoField(primary_key=True, serialize=False)),
                ('nombretipocamara', models.CharField(max_length=100)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipocamara',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipousuarios',
            fields=[
                ('idtipousuarios', models.AutoField(primary_key=True, serialize=False)),
                ('nombreidtipousuarios', models.CharField(max_length=100)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipousuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombreusuario', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100, unique=True)),
                ('dniusuario', models.IntegerField()),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('admin', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
