# Generated by Django 5.2.2 on 2025-06-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detallepersonacamara',
            fields=[
                ('iddetallepc', models.AutoField(db_column='idDetallePC', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detallePersonaCamara',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personarq',
            fields=[
                ('idpersona', models.AutoField(db_column='idPersona', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('dni', models.IntegerField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personaRQ',
                'managed': False,
            },
        ),
    ]
